feat: testing gha

diff --git a/.github/workflows/release-please.yaml b/.github/workflows/release-please.yaml
--- a/.github/workflows/release-please.yaml
+++ b/.github/workflows/release-please.yaml
@@ -44,54 +44,75 @@ jobs:
       #   uses: helm/chart-releaser-action@v1.5.0
       #   env:
       #     CR_TOKEN: ${{ steps.generate_token.outputs.token }}
-  get-chart:
+  get-bumped-charts:
     runs-on: ubuntu-latest
-    # needs: release-please
+    needs: release-please
+    if: ${{ needs.release-please.outputs.releases_created }}
     name: 'Get modified charts'
     permissions:
       contents: read
     outputs:
-      chart: ${{ steps.get-chart.outputs.chart }}
-      result: ${{ steps.get-chart.outputs.result }}
+      charts: ${{ steps.get-bumped-charts.outputs.charts }}
+      result: ${{ steps.get-bumped-charts.outputs.result }}
     steps:
       - uses: actions/checkout@v3
         with:
           path: charts
           fetch-depth: 2 # to be able to obtain files changed in the latest commit
-      - id: get-chart
+      - id: get-bumped-chart
         name: 'Get modified charts'
         run: |
           cd charts
+          # get the changed files
           files_changed="$(git show --pretty="" --name-only)"
-          # Adding || true to avoid "Process exited with code 1" errors
-          charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep -o "charts/[^/]*" | sort | uniq || true)"
 
-          echo "changed ------------> $charts_dirs_changed"
+          # get the directories that includes Chart.yaml file changes to get the charts that changed version
+          chart_file_changed="$(echo $files_changed | grep -E 'Chart\.ya?ml' | xargs dirname | grep -o "charts/[^/]*" | sort | uniq || true)"
 
-          # Using grep -c as a better alternative to wc -l when dealing with empty strings."
-          num_charts_changed="$(echo "$charts_dirs_changed" | grep -c "charts" || true)"
-          num_version_bumps="$(echo "$files_changed" | grep Chart.yaml | xargs git show | grep -c "+version" || true)"
+          # Initialize an empty array for version-changed charts
+          version_changed_charts=()
 
-          if [[ "$num_charts_changed" -ne "$num_version_bumps" ]]; then
-            # Changes done in charts but version not bumped -> ERROR
-            charts_changed_str="$(echo ${charts_dirs_changed[@]})"
-            echo "error=Detected changes in charts without version bump in Chart.yaml. Charts changed: ${num_charts_changed} ${charts_changed_str}. Version bumps detected: ${num_version_bumps}" >> $GITHUB_OUTPUT
-            echo "result=fail" >> $GITHUB_OUTPUT
-          elif [[ "$num_charts_changed" -eq "1" ]]; then
-            # Changes done in only one chart -> OK
-            chart_name=$(echo "$charts_dirs_changed" | sed "s|charts/||g")
-            echo "chart=${chart_name}" >> $GITHUB_OUTPUT
-            echo "result=ok" >> $GITHUB_OUTPUT
+          for chart in $chart_file_changed; do
+            # Check if there's a version change in the Chart.yaml file
+            if git show "$chart" | grep -q "+version"; then
+              version_changed_charts+=("$chart")
+            fi
+          done
+          
+          # make the outputs
+          if [ ${#version_changed_charts[@]} -gt 0 ]; then
+            chart_names=$(printf "%s\n" "${version_changed_charts[@]}")
+            echo "charts=${version_changed_charts[@]}" >>$GITHUB_OUTPUT
+            echo "result=ok" >>$GITHUB_OUTPUT
           else
-            # Changes done in more than chart -> FAIL
-            charts_changed_str="$(echo ${charts_dirs_changed[@]})"
-            echo "error=Changes detected in more than one chart directory: ${charts_changed_str}. The publish process will be stopped. Please create different commits for each chart." >> $GITHUB_OUTPUT
-            echo "result=fail" >> $GITHUB_OUTPUT
+            echo "error=No version changed charts found" >>$GITHUB_OUTPUT
+            echo "result=fail" >>$GITHUB_OUTPUT
           fi
+
+          # print the outputs
+          cat $GITHUB_OUTPUT
       - id: show-error
         name: 'Show error'
-        if: ${{ steps.get-chart.outputs.result == 'fail' }}
+        if: ${{ steps.get-bumped-charts.outputs.result == 'fail' }}
         uses: actions/github-script@v6
         with:
           script: |
-              core.setFailed('${{ steps.get-chart.outputs.error }}')
+              core.setFailed('${{ steps.get-bumped-charts.outputs.error }}')
+  publish-charts:
+    runs-on: ubuntu-latest
+    needs: get-bumped-charts
+    if: ${{ needs.get-bumped-charts.outputs.result == 'ok' }}
+    name: Publish Charts
+    permissions:
+      contents: read
+    steps:
+      - uses: actions/checkout@v3
+        name: Checkout Repository
+      - id: test
+        name: test
+        run: |
+          bumped_charts=${{needs.get-bumped-charts.outputs.charts}}
+          for chart_dir in bumped_charts; do
+            cd $chart_dir
+            cat Chart.yaml
+          done
